worker_processes auto;

pid /run/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_body_temp_path /var/lib/nginx/tmp/client_body;
    proxy_temp_path       /var/lib/nginx/tmp/proxy;
    fastcgi_temp_path     /var/lib/nginx/tmp/fastcgi;
    uwsgi_temp_path       /var/lib/nginx/tmp/uwsgi;
    scgi_temp_path        /var/lib/nginx/tmp/scgi;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_types
      text/plain
      text/css
      application/json
      application/javascript
      text/xml
      application/xml
      application/xml+rss
      text/javascript
      application/atom+xml
      application/vnd.ms-fontobject
      application/x-font-ttf
      application/x-web-app-manifest+json
      application/xhtml+xml
      font/opentype
      image/svg+xml
      image/x-icon
      text/x-component;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_disable "msie6";

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    server {
        listen 8080 default_server;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location /healthz {
            access_log off;
            add_header Content-Type text/plain;
            return 200 'OK';
        }

        location ~ ^/assets/ {
            access_log off;
        }

        location = /manifest.json {
            try_files $uri =404;
        }

        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|avif|webp)$ {
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }

        location ~* \.(html)$ {
            expires 1h;
            add_header Cache-Control "public, max-age=3600";
        }

        location ~* \.(js|css|html|json|svg|xml|wasm)$ {
            add_header Content-Encoding br;
            add_header Vary Accept-Encoding;
            gzip off;
            try_files $uri.br $uri;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}

