# Entorno pre / desarrollo — ajusta namespace, registry e ingress a tu cluster
namespace: pre-jf-homepage-front
replicaCount: 1
registry: harbor.server.local/danielbeltejar/personal-portfolio
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
extraEnv:
  - name: "TZ"
    value: "UTC"
extraEnvFrom: []
resources:
  requests:
    memory: "64Mi"
    cpu: 100m
  limits:
    cpu: 500m
    memory: "256Mi"
volumes:
  - name: tmpfs-var-lib-nginx-tmp
    emptyDir:
      medium: Memory
  - name: tmpfs-run-nginx
    emptyDir:
      medium: Memory
volumeMounts:
  - name: tmpfs-var-lib-nginx-tmp
    mountPath: /var/lib/nginx/tmp
  - name: tmpfs-run-nginx
    mountPath: /run/nginx
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-set-header: X-Real-IP $remote_addr
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-ovh
  class: "nginx-local"
  host: "jf-homepage.pre.danielbeltejar.es"
  tls: true

